# Generated by Django 5.1.7 on 2025-03-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
