# Generated by Django 5.1.7 on 2025-03-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_service_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='bio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='post',
            field=models.CharField(default='your post', max_length=255),
        ),
    ]
